### ISSUE TITLE
Using search with multiple sources does not return info from non-european databases

### ISSUE THREAD

**Issue by Dominik-Czulak** [RIPE-NCC/whois#1020]
Until a while a go (uncertain when exactly but probably around 2-3 months) using the rest api with the search function on non-eu ip addresses would return the object information. Now it just says to go to the other databases with website information (also tried this with multiple sources).
Example query:

https://rest.db.ripe.net/search.json?arin-grs&query-string=8.8.8.8&type-filter=inetnum&type-filter=inet6num

I would expect it to work similar as described in point 4 in https://www.ripe.net/manage-ips-and-asns/db/support/querying-the-ripe-database
![image](https://user-images.githubusercontent.com/79507763/169999435-6f2dcbc5-693d-4d91-8616-653755bb792d.png)

Is this intended behaviour, is there still a way to get information on non-eu addresses directly through the rest api or am I doing something wrong?

**Comment by eshryane** [comment]
Hi @Dominik-Czulak 

From point 4 in the referenced documentation:
```
Using the API, you can specify one or multiple GRS source names as parameters, e.g. "source=arin-grs" or "source=arin-grs&source=apnic-grs". 
For more information, please refer to the [documentation on Github](https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-search).
```

In your example, you're using "arin-grs" as a query parameter *name*, but you need to use "source=arin-grs" instead.

Re-writing your example as:
https://rest.db.ripe.net/search.json?source=arin-grs&query-string=8.8.8.8&type-filter=inetnum&type-filter=inet6num

does return the 8.8.8.0/24 inetnum object from ARIN-GRS.

You can add multiple "source" query parameters for multiple GRS sources, or you can use "flags=resource" to search in *all* GRS mirror sources, i.e.

https://rest.db.ripe.net/search.json?query-string=8.8.8.8&type-filter=inetnum&type-filter=inet6num&flags=resource

Hope this helps.

**Comment by Dominik-Czulak** [comment]
Ah yes you are right, it was a bad example as I deleted the multiple sources from the link before I posted it and accidentally deleted the "source=" string. The resource flag is a good tip thank you.

But I guess my main issue is that except for the "inetnum", "netname"  and "status" I don't get any other information (like description/address). So in order to get this info I would have to query ARIN separately? Or is there a way to get it directly with this API? 
I'm not entirely sure, but I think it used to return more information about non-eu ips when querying a few months ago.

**Comment by eshryane** [comment]
Hi @Dominik-Czulak 

Yes you only see essential attributes from objects in the GRS sources, we have to strip out any attributes that could possibly contain personal data. You need to query the authoritative (original) source to see the entire object.

Nothing has changed recently in this regard, this is how our GRS sources have always worked.

You can use RDAP to query for a resource, this service will automatically redirect you to the authoritative source:
https://www.ripe.net/manage-ips-and-asns/db/registration-data-access-protocol-rdap

But, objects returned by RDAP are also filtered.

**Comment by Dominik-Czulak** [comment]
Thank you very much! This helps a lot.
