### ISSUE TITLE
Wiki REST docs - mention filtering of responses

### ISSUE THREAD

**Issue by nigelm** [RIPE-NCC/whois#1060]
The wiki information on the REST interface should:-

- mention that the results are, by default, filtered as per https://apps.db.ripe.net/docs/13.Types-of-Queries/06-Filtering-the-Query-Reponse.html
- add the information that adding `unfiltered` as a query parameter removes the default filtering

This information does not appear to be visible anywhere currently.

[If you want a MR or similar for this then please let me know]

**Comment by eshryane** [comment]
Hello @nigelm thanks for your report and apologies it's taken so long for an update. I've added this issue to our documentation repository. I'll keep you informed of any progress.

Also the referenced document has moved to:
https://apps.db.ripe.net/docs/13.Types-of-Queries/08-Filtering-the-Query-Reponse.html

**Comment by eshryane** [comment]
Hi @nigelm we have now updated the REST API documentation:
https://apps.db.ripe.net/docs/How-to-Query-the-RIPE-Database/RESTful-API-Queries/
to mention:
"By default objects are filtered as described in Filtering the Query Response."

Also the REST API lookup (GET method) section:
https://apps.db.ripe.net/docs/How-to-Query-the-RIPE-Database/RESTful-API-Queries/#rest-api-lookup
mentions:
"unfiltered: The returned object should not be filtered ("notify" and "e-mail" attributes will not be removed)."
