### ISSUE TITLE
Query RDAP for AS-SET

### ISSUE THREAD

**Issue by jwbensley** [RIPE-NCC/whois#1089]
[This page](https://www.ripe.net/manage-ips-and-asns/db/registration-data-access-protocol-rdap) states in the table that one can query using the `autnum` for an AS-SET but when I look in the RFCs and at other RDAP DBs querying for AS-SET isn't mentioned, and I can't get this to work with RIPE.

Is this a mistake in the documentation or does it in fact work and this is a case of [pebkac](https://en.wiktionary.org/wiki/PEBCAK) at my end?

**Comment by eshryane** [comment]
Hi @jwbensley it's a mistake in the documentation, we are going to correct it, thanks for pointing it out.

**Comment by MiguelAHM** [comment]
Hi @jwbensley, sorry for the inconvenience and thank you for the given feedback. The documentation should now be fixed.
