### ISSUE TITLE
whois-nrtm4 failure on compile

### ISSUE THREAD

**Issue by zionjfd** [RIPE-NCC/whois#1318]
Hi,
i have a issue and cannot pass this stage:

ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.478 s <<< FAILURE! - in net.ripe.db.nrtm4.scheduler.NrtmV4InitializerJmxTest

[ERROR] Errors: 
[ERROR]   NrtmV4InitializerJmxTest.shouldInitializeNrtmv4 » Mockito 
Mockito cannot mock...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for whois 1.0-SNAPSHOT:
[INFO] 
[INFO] whois .............................................. SUCCESS [  2.793 s]
[INFO] whois-rpsl ......................................... SUCCESS [ 24.999 s]
[INFO] whois-client ....................................... SUCCESS [ 11.061 s]
[INFO] whois-commons ...................................... SUCCESS [ 22.387 s]
[INFO] whois-query ........................................ SUCCESS [ 26.176 s]
[INFO] whois-nrtm ......................................... SUCCESS [ 24.061 s]
[INFO] whois-update ....................................... SUCCESS [01:40 min]
[INFO] whois-nrtm4 ........................................ FAILURE [  6.669 s]
[INFO] whois-api .......................................... SKIPPED
[INFO] whois-scheduler .................................... SKIPPED
[INFO] whois-db ........................................... SKIPPED
[INFO] whois-endtoend ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Is sombody already get this error
bets regards

**Comment by eshryane** [comment]
Hello @zionjfd can you pull the latest changes and try again? Are you running `maven clean install` ?

**Comment by eshryane** [comment]
Also, please run the `maven` command from the root (whois) directory

**Comment by zionjfd** [comment]
Hi,

Going to pull the latest and let u you.

About "maven clean install" yes i do

**Comment by zionjfd** [comment]
Hi,

after pulling the latest changes, get the same issue compliling  in the whois root directory

**Comment by eshryane** [comment]
Hi @zionjfd can you attach the output of `mvn -X clean install` please ?

**Comment by zionjfd** [comment]
[mvn-output.txt.gz](https://github.com/RIPE-NCC/whois/files/13393812/mvn-output.txt.gz)

Hi,
You'l find the output in atttachment,
thank you for the debug

**Comment by eshryane** [comment]
Relevant output:
```
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: class net.ripe.db.nrtm4.scheduler.SnapshotFileScheduledTask.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 19
JVM vendor name    : Private Build
JVM vendor version : 19.0.2+7-Ubuntu-0ubuntu322.04
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 19.0.2+7-Ubuntu-0ubuntu322.04
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 5.15.0-87-generic


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.lang.Runnable, class java.lang.Object, class net.ripe.db.nrtm4.scheduler.SnapshotFileScheduledTask, interface net.ripe.db.whois.common.scheduler.DailyScheduledTask]
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.lang.Runnable, class java.lang.Object, class net.ripe.db.nrtm4.scheduler.SnapshotFileScheduledTask, interface net.ripe.db.whois.common.scheduler.DailyScheduledTask]
Caused by: java.lang.IllegalStateException: 

Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
```

**Comment by eshryane** [comment]
@zionjfd You're using Java 19 but we're still on 17. Can you try switching to Java 17 ?

**Comment by zionjfd** [comment]
Ok, goin to downgrade it and make a try, thank you
i'l let you know

**Comment by eshryane** [comment]
Java 21 is now the latest LTS version since September 23rd, we plan to upgrade but haven't done so yet.

**Comment by zionjfd** [comment]
it's because i'am on ubuntu 22.04 so i have install  the latest java, i will try to install an older package

**Comment by eshryane** [comment]
Thanks for checking @zionjfd good to hear. We plan to upgrade to Java 21 in the coming months.
