### ISSUE TITLE
How mail-update works?

### ISSUE THREAD

**Issue by gonghewan** [RIPE-NCC/whois#1526]
It looks like whois only tries to read from mysql(table 'mailupdates') to get a mail-update message request and then handle it. I don't know if my understanding is correct or not.If not, how does the whois server catch mail-update requests? 

In addition, I noticed that MailMessageDaoJdbc.addMessage() aims to insert mail-update messages into mysql(table 'mailupdates'), but I didn't find any other class or function to call it. Do I need to implement the logic of reading emails from the mailbox and inserting them into the database separately? Or there already exists a function of whois to read from the mailbox?

**Comment by eshryane** [comment]
We insert mailupdates messages into the mailupdates table outside of the Whois software, by a local user that processes incoming mail messages. There is an external script called by maildrop containing a SQL INSERT statement which inserts the mail message into the database.

For example, the script looks something like this:
```
set -e(echo -ne 'INSERT INTO mailupdates (message, changed) VALUES (0x'hexdump -ve '1/1 "%.2x"'echo -ne ', UNIX_TIMESTAMP())') \| mysql -hserver.ripe.net \
 -umailupdates \
 -p'password' \
 -s MAILUPDATES_RIPE &>> $1
```

I hope this answers your question.

**Comment by gonghewan** [comment]
Hello Shryane,

It's really helpful for us, sincerely thanks for your reply.


Ed Shryane ***@***.***> 于2024年9月17日周二 20:27写道：
