### ISSUE TITLE
silently ignores EOL comment on pkey

### ISSUE THREAD

**Issue by ripe-denis** [RIPE-NCC/whois#196]
If an update includes an end of line comment on the pkey it is silently ignored and stripped off. It should be reported as being stripped off.

If that is the only change, no update is done to the object in the DB (it is a NOOP) but the result in Webupdates still says "Object successfully updated! "

**Comment by timbru** [comment]
We now include a warning: Please use the "remarks:" attribute instead of end of line comment on primary key.
