### ISSUE TITLE
Allow more than 250 results in Web Query

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#219]
Currently, a maximum of 250 objects are displayed in the web query results.

For example:
- Go to https://apps.db.ripe.net/search/query.html
- Search for "-M 193/8"
- Get warning: Too many results. The first 250 are displayed.

Enhancement:
- Display the actual number of matched objects (but still only display 250 by default).
- Warn the user that displaying all results will be time- and memory- consuming.
- Allow the user to confirm they want to see all results.

Workaround:
- Use the command-line interface (whois.ripe.net port 43)
- Use the REST API search function (https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-search)

**Comment by timbru** [comment]
Won't fix for now. Not an urgent problem. The user can refine the search or use XML/json if they intend to really parse all objects.
