### ISSUE TITLE
Query error messages have a newline at the end

### ISSUE THREAD

**Issue by agoston** [RIPE-NCC/whois#239]
Historically, the error messages coming from QueryMessages have a newline at the end, while the rest of the code (UpdateMessages, RestMessages, ValidationMessages) doesn't.

We should be consistent over this and drop this extra newline from the QueryMessages too.

NB: this is simply removing a ` + "\n"` in QueryMessage 's contructor, but we should announce this change and make sure dbwebwar is working without the newlines, too.

**Comment by timbru** [comment]
Since this can affect existing deployment I believe we should not do this just for the sake of consistency.
