### ISSUE TITLE
Error page with exception message displayed when there is no connectivity with REST services

### ISSUE THREAD

**Issue by tpolychniatis** [RIPE-NCC/whois#242]
When there is no connectivity with one of the two sources for REST services, and an operation is submitted, the error page is displayed with a cryptic error message such as NullPointerException, or Internal Software Error. 

We should provide a more descriptive error message instead, either on the same page, or on the general error page.

**Comment by eshryane** [comment]
Re-tested with Angular webupdates application - now if there is no internet connectivity, nothing happens when the Submit button is clicked. We should display an error.

**Comment by timbru** [comment]
Closing this here. If issues like this come up, just raise them during the sprint please and we can just fix, or prioritise.
