### ISSUE TITLE
allow creation of /7 ROUTE object

### ISSUE THREAD

**Issue by ripe-denis** [RIPE-NCC/whois#249]
To be consistent with RIPEstat we should move the limit on size of ROUTE object creation to allow a max size of /7

See db-support ticket #1084384

**Comment by timbru** [comment]
No, the US DOD has two consecutive /7s, but I don't think there is any business need for this in the RIPE whois software. So even though it should not be much work, I don't see a reason to do this unless requested by the real owner of a /7 or bigger.
