### ISSUE TITLE
Query for inetnum doesn't return matching inet-rtr object on ifaddr attribute

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#277]
query for:

<ip-lookup> (IPv4 address prefix, range or single address) 

should give:

inetnum and/or route objects with exact match between the primary key and query argument. If the exact match objects do not exist, the objects with the smallest less specific primary key that match are returned. __When you specify a single address, an inet-rtr object whose “ifaddr:” attribute matches the query argument is also returned.__

Taking the object:

inet-rtr:       kst1-core.swip.net
local-as:       AS1257
ifaddr:         146.188.49.14 masklen 30
ifaddr:         195.158.247.62 masklen 30
peer:           BGP4 146.188.49.13 asno(AS702)
peer:           BGP4 195.158.247.61 asno(AS1755)
admin-c:        LMJ1-RIPE
tech-c:         JS17577-RIPE
mnt-by:         AS1257-MNT
changed:        jonas@swip.net 20010424
source:         RIPE

whois -rBG 146.188.49.14
should return this object, but it doesn't.

**Comment by timbru** [comment]
closing this for now, but can re-prioritise if users report this as an issue
