### ISSUE TITLE
Persistent connection not closed on an empty query

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#278]
The Whois documentation states:

*To exit a persistent connection, send the “-k” or “--persistent-connection”  flag with no query argument or an empty query (\n) to the server.*

However, sending an empty query doesn't close a persistent connection.

Ref. http://www.ripe.net/data-tools/support/documentation/ripe-database-documentation-1.7.6/types-of-queries/16-8-persistent-connections-and-keeping-state

**Comment by timbru** [comment]
Although this not resolved, I feel that this is very low priority.

If users experience problems with this please report so we can re-prioritise.

For now, closing this one.
