### ISSUE TITLE
RPSL Objects containing blank lines are syntactically incorrect

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#284]
RPSL objects containing blank lines (with only tabs and/or spaces) are not syntactically incorrect.

Whois currently accepts these objects, which causes problems when the object is then read out of the database (e.g. by NRTM).

Either fix these objects, or reject the update as incorrect.

**Comment by eshryane** [comment]
This has been fixed in Whois 1.76.1.

If a blank line is found in an attribute, it is converted into a '+' continuation character, as per RFC 2622.

Ref. http://www.ripe.net/data-tools/db/release-notes/ripe-database-release-1.76.1

**Comment by timbru** [comment]
We have approached the party sending these updates.

However, we believe that we can safely recognises and convert intended blank lines to the correct RFC format as Ed commented above. Therefore we chose to fix these objects on input rather than reject them.
