### ISSUE TITLE
Pending Create Route requests are not Removed when the Route is Created

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#286]
Creating route objects needs authorisation from both the IP address space, and the AS resource:

http://www.ripe.net/data-tools/db/faq/faq-db/what-are-the-authorisation-rules-for-route-object-creation

If a create request is not completely authorised, it is pended for a week:

https://labs.ripe.net/Members/denis/simplified-route-creation-in-the-ripe-database

When the route is created, any pending requests should be removed immediately. However this doesn't always happen, and incorrect / confusing emails are generated when the request is cleaned up later.

**Comment by eshryane** [comment]
Related to #257

**Comment by MarcGrol** [comment]
In case second, confirming maintainer is authorised to adjust both autnum and inetnum the pending authorisation was not cleaned up. 
(Fixed by commit f648434bd3f637126f80d14360d0d53daa0dc6d6)
