### ISSUE TITLE
jsonp does not work with ripe api because of missing callback prefix

### ISSUE THREAD

**Issue by ritterstation** [RIPE-NCC/whois#289]
When calling the API like

https://rest.db.ripe.net/search.json?type-filter=inetnum&source=ripe&query-string=8.8.8.8

and call it via jsonp it should give back the callback-parameter in GET as the prefix of the JSON output.

This should be easy. Is there a possibility to correct this?

**Comment by timbru** [comment]
We don't see an easy way to do this.

**Comment by asmeureanu** [comment]
Hi,

I am facing the same problem. I would really like to point again to this issue! It can be this diffcult
It is very important to provide a proper JSONP otherwise the CORS will stops any integration on the browser side from javascript.

**Comment by timbru** [comment]
We don't see why we should support showing (or worse even updating) RIPE Database content through third party websites. We believe it to be more secure if users query (and update) using our authoritative interface. In addition to this, there are several security concerns with regards to the (naive) use of jsonp if one was to support such a thing.
