### ISSUE TITLE
Query for a specific IP address

### ISSUE THREAD

**Issue by psinghsp** [RIPE-NCC/whois#290]
ARIN provides a REST API which can provide information an individual IPv4 address. Is there a way to get this info using RIPE REST APIs?

Following does not seem to work:
http://rest.db.ripe.net/ripe/inetnum/2.2.2.2.json

**Comment by MarcGrol** [comment]
To search for resources:
in xml-format: http://rest.db.ripe.net/search?query-string=2.2.2.2
or
in json-format: http://rest.db.ripe.net/search.json?query-string=2.2.2.2

To get the details of a known resource (NB: have to address it using its unique identifier):
in xml-format: http://rest.db.ripe.net/ripe/inetnum/2.0.0.0-2.15.255.255 
or
in json-format: http://rest.db.ripe.net/ripe/inetnum/2.0.0.0-2.15.255.255.json

More details on the rest interface can be found at https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
