### ISSUE TITLE
No warning on conversion to latin-1 character set

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#291]
RPSL objects are stored internally using the latin-1 (ISO-8859-1) character set.

If an object is submitted that uses another character set, the object is converted to latin-1. If a character doesn't exist in the latin-1 character set, the replacement character '?' (question mark, 0x3F) is used instead.

The whois application should warn the user when an object is updated, if any substitution of replacement characters was made. Sometimes this is not done.

Ref. commit 1c5bf004 for test cases.

**Comment by timbru** [comment]
closing this pending the discussion on utf-8 in the working group

**Comment by eshryane** [comment]
This was recently fixed in 1.87.5, with the changes to RPSL object processing. 
Ref. 6d56305a05e17de5db83dd16dbf7fbf4d9bdd647
