### ISSUE TITLE
Adding a session password cannot be done by clicking on the Add button.

### ISSUE THREAD

**Issue by tpolychniatis** [RIPE-NCC/whois#293]
In the Delete page in Webupdates, adding a session password cannot be done by clicking on the Add button next to the password box, but only by hitting the Enter key.

To reproduce:
1. Search for an object in the query page, e.g.:
https://apps.db.ripe.net/search/query.html?searchtext=193.0.0.1&rflag=true&source=RIPE
2. From the search results, click on the Delete button in one of the objects.
3. Add a session password and try to click on Add. <-- it does not work.

As  work around enter a session password and hit on the enter key from the keyboard. 
Note: if a password is added via the enter key, the Add button becomes clickable again.

**Comment by timbru** [comment]
We are working on improving web updates using SSO accounts. When this is done there will be no more need to store passwords in the session.
