### ISSUE TITLE
NRTM connection is immediately retried when not authorized

### ISSUE THREAD

**Issue by benkovsk** [RIPE-NCC/whois#294]
When I run the software configured as an NRTM client and its connections to nrtm.ripe.net are denied due to unauthorised IP address (%ERROR:402: not authorised to mirror the database from IP address XXX.XXX.XXX.XXX), the local whois immediately retries the connection again and again (250 connections in 10 seconds). Should not the connection attempts be throttled?

Tested with the current master, 3e4b5451

**Comment by eshryane** [comment]
Thanks for reporting, this is similar to #279 (which you also reported, last November).

You're correct, we should just not retry after certain exceptions.

**Comment by timbru** [comment]
I agree that it would be better and created an issue in our internal planning tool - however, I believe that the priority of doing this is low compared to many of the other issues on our list.

Please let us know if this is causing serious issues for you.
