### ISSUE TITLE
DB schema is missing version tables and appropriate records

### ISSUE THREAD

**Issue by benkovsk** [RIPE-NCC/whois#295]
When starting the server, console.log contains tracebacks due to some databases missing version tables, or some version tables missing the version records:

> org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT version FROM version]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'DNSCHECK_CZNIC.version' doesn't exist

> 2015-06-18 13:04:31,835 WARN  [DatabaseVersionCheck] Error checking datasource sourceAwareDataSource/RIPE-GRS [SLAVE]
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0

The server starts without problems, however.

**Comment by timbru** [comment]
Closing this issue since it seems that it doesn't cause problems.
