### ISSUE TITLE
NRTM doc problem: Bootstrap imports to LOCAL, not RIPE-GRS

### ISSUE THREAD

**Issue by benkovsk** [RIPE-NCC/whois#296]
The documentation at https://github.com/RIPE-NCC/whois/wiki/Setup-a-RIPE-GRS-mirror-using-Bootstrap-and-NRTM implies, that by importing ripe.db.gz using Bootstrap bean, data are imported to WHOIS_MIRROR_RIPE_GRS database:

    When the import is finished exit the jmx console, and test that it worked by executing a query using telnet:

    telnet localhost 1043
    -s RIPE-GRS 193.0.0.1 - 193.0.7.255

In reality, the above check returns %ERROR:101: no entries found , because the database was imported to the local database (WHOIS_CZNIC in our case). So unless there is more dark magic based on database name, the NRTM doc above is incomplete and one has to follow the bootstrap with database dump, dropping the local database and reimporting the backup to RIPE-GRS database. Or am I missing something?

Better solution would be, of course, to specify the database to which the bootstrap imports ripe.db.gz during the bootstrap.

**Comment by tpolychniatis** [comment]
Thanks for reporting the issue.
we know that setting up NRTM is not as straight forward as we would like to be. NRTM is not used by many users and it is a matter of priorities what we work on. 

As for the specific issue, there is some "magic" connecting source name and database names, and  that is why we wrote in the instructions that the specific database names should be used. Please, try to use the same database names as described in the instructions, and follow the final part too (https://github.com/RIPE-NCC/whois/wiki/Setup-automatic-updating-with-NRTM). 

We will also setup NRTM and correct the documentation accordingly.

**Comment by tpolychniatis** [comment]
Hi,
Indeed there were missing steps in the instructions. I updated them to make the process somewhat easier!
