### ISSUE TITLE
Abuse finder page does not recognise IPv6 addresses with zeros not grouped.

### ISSUE THREAD

**Issue by tpolychniatis** [RIPE-NCC/whois#299]
To reproduce:
- Go to Abuse finder https://apps.db.ripe.net/search/abuse-finder.html
- Lookup valid IPv6 address 2001:67c:2e8:0:0:0:0:0/48 or 2001:067c:02e8:0000:0000:0000:0000:0000/48 fails with error:  "The key must be an AS Number, IPV4 or IPV6 address.".
- Lookup with another form of the same address 2001:67c:2e8::/48 succeeds.

**Comment by eshryane** [comment]
This is fixed, and will be included in the next release.
