### ISSUE TITLE
invalid mp-import value

### ISSUE THREAD

**Issue by eshryane** [RIPE-NCC/whois#305]
The following mp-import attribute value is invalid, but is accepted by Whois:

afi ipv6.unicastfrom AS39790 action pref=150; accept AS39790

**Comment by eshryane** [comment]
Spaces, tabs and newlines are ignored by all of the attribute lexers. So "ipv6.unicastfrom" produces the tokens "ipv6.unicast" and "from", and the space is dropped.

**Comment by eshryane** [comment]
irrtoolset (rpslcheck) correctly marks this attribute as incorrect:

mp-import:      afi ipv6.unicastfrom AS39790 action pref=150; accept AS39790
                    ^^^^^^^^^^^^^^^^
***Error: wrong mp-import.

**Comment by hhazewinkel** [comment]
See branch import-bug-II

**Comment by eshryane** [comment]
Merged fix 48876c6 to master. This fix will be included in the next Whois release 1.87.
