### ISSUE TITLE
RDAP missing CORS header

### ISSUE THREAD

**Issue by codebje** [RIPE-NCC/whois#307]
The RDAP server running at rdap.db.apnic.net is not adding Access-Control-Allow-Origin headers, against the recommendation of RFC 7480 s5.6.  This means it can't be queried by scripts running in web pages.

**Comment by eshryane** [comment]
Hey Byron,

we recently added a CrossOriginFilter class, which currently only accepts .ripe.net origins:

https://github.com/RIPE-NCC/whois/blob/master/whois-api/src/main/java/net/ripe/db/whois/api/rest/CrossOriginFilter.java

This could be modified, and added to:

https://github.com/RIPE-NCC/whois/blob/rdap/whois-api/src/main/java/net/ripe/db/whois/api/whois/rdap/WhoisRdapServletDeployer.java

**Comment by codebje** [comment]
Hey Ed,

I'm doing ASN lookups from a web page, and currently it works for ASNs in all regions except RIPE, because RIPE's service doesn't have an appropriate CORS header.  I'm not sure you'd call it a bug with the code, so much as an issue with the deployment or operation of RIPE's RDAP service - so perhaps github isn't the best place for this?

**Comment by eshryane** [comment]
Thanks, I've committed a TODO on the rdap branch (dc1a864f55cba4ef6c2f3a93b922a405746b8400). We plan to work further on our rdap implementation soon, I think this issue can remain open until we address it.

**Comment by eshryane** [comment]
Created pull request with a fix #412

**Comment by eshryane** [comment]
Merged into rdap branch, and deployed to https://rdap.db.ripe.net.

**Comment by eshryane** [comment]
Thanks Byron, I've re-opened the issue.

**Comment by eshryane** [comment]
Until this is fixed in Whois, I made a temporary proxy change to include "Access-Control-Allow-Origin: *" in RDAP responses (if Origin is not specified in the request).

**Comment by eshryane** [comment]
Confirmed fixed.
