### ISSUE TITLE
Can't modify domain attributes

### ISSUE THREAD

**Issue by rjma30** [RIPE-NCC/whois#320]
Hello,

I'm getting Invalid object type: descr" error when trying to modify the descr attribute.

My xml input is:

`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>`
`<whois-resources>`
  `<objects>`
    `<object type="domain">`
      `<source id="ripe"/>`
      `<attributes>`
        `<attribute name="descr" value="Regusnet customer address space _"/>`
      `</attributes>`
    `</object>`
  `</objects>`
`</whois-resources>`

[root@phnetaxs02 ripe]# curl -v -X PUT -H 'Content-Type: application/xml' --data @input.xml 'https://rest.db.ripe.net/ripe/domain/10.152.90.in-addr.arpa?password=xxxxxxxxx'

`* About to connect() to rest.db.ripe.net port 443 (#0)`
`*   Trying 193.0.6.142... connected`
`* Connected to rest.db.ripe.net (193.0.6.142) port 443 (#0)`
`* Initializing NSS with certpath: sql:/etc/pki/nssdb`
`*   CAfile: /etc/pki/tls/certs/ca-bundle.crt`
`  CApath: none`
`* SSL connection using TLS_DHE_RSA_WITH_AES_256_CBC_SHA`
`* Server certificate:`
`*       subject: CN=*.db.ripe.net,O=RIPE NCC,L=Amsterdam,ST=Noord-Holland,C=NL`
`*       start date: Jul 10 00:00:00 2015 GMT`
`*       expire date: Aug 25 12:00:00 2016 GMT`
`*       common name: *.db.ripe.net`
`*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US`
`> PUT /ripe/domain/10.152.90.in-addr.arpa?password=xxxxxxxxx HTTP/1.1`
`> User-Agent: curl/7.19.7 (i386-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2`
`> Host: rest.db.ripe.net`
`> Accept: */*`
`> Content-Type: application/xml`
`> Content-Length: 289`
`> `
`< HTTP/1.1 400 Bad Request`
`< Date: Tue, 01 Dec 2015 12:13:26 GMT`
`< Server: Jetty(8.y.z-SNAPSHOT)`
`< Content-Length: 342`
`< Content-Type: application/xml`
`< Cache-Control: no-cache, no-store, must-revalidate`
`< Pragma: no-cache`
`< Expires: 0`
`< Vary: Accept-Encoding`
`< Connection: close`
`< `
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><whois-resources xmlns:xlink="http://www.w3.org/1999/xlink"><errormessages><errormessage severity="Error" text="Invalid object type: descr"/></errormessages><terms-and-conditions xlink:type="locator" xlink:href="http://www.ripe.net/db/support/db-terms-conditions.pdf"/></whois-resources>`
`* Closing connection #0`
`[root@phnetaxs02 ripe]#`

Thank you!

**Comment by eshryane** [comment]
I've reproduced this, we are parsing the first attribute as the object type. The response message is confusing.

**Comment by eshryane** [comment]
BTW - to modify the descr: attribute, you will need to submit the entire object. For example:

`<whois-resources>`
`    <objects>`
`        <object type="domain">`
`            <source id="RIPE"/>`
`            <attributes>`
`                <attribute name="domain" value="0.0.193.in-addr.arpa."/>`
`                <attribute name="descr" value="domain description updated"/>`
`                <attribute name="admin-c" value="TP1-TEST"/>`
`                <attribute name="tech-c" value="TP1-TEST"/>`
`                <attribute name="zone-c" value="TP1-TEST"/>`
`                <attribute name="nserver" value="ns1.ripe.net"/>`
`                <attribute name="nserver" value="ns2.ripe.net"/>`
`                <attribute name="mnt-by" value="OWNER-MNT"/>`
`                <attribute name="source" value="TEST"/>`
`            </attributes>`
`        </object>`
`    </objects>`
`</whois-resources>`

**Comment by rjma30** [comment]
Thanks eshryane!

Do I need to submit the entire object as well if I want to modify tech-c and zone-c?

**Comment by eshryane** [comment]
Yes - for any create or update operation, you must provide the entire object (for delete you can leave the body empty).

One way is to first lookup an existing object using a GET request, modify the response object, and submit using a PUT request.

**Comment by rjma30** [comment]
Thanks again!

**Comment by rjma30** [comment]
Hello again,

I'm now getting below error which I do not get when updating thru web.

` <errormessages>
        <errormessage severity="Error" text="2 different SOA records found.&#xA;&#xA;The other fields in the SOA record are not the same among all name servers. This is usually due to misconfiguration."/>
        <errormessage severity="Warning" text="Could not find reverse address for 77.95.81.112 (112.81.95.77.in-addr.arpa.).&#xA;&#xA;PTR record(s) for the address could not be found in the .arpa-zone. (ip6.arpa. for IPv6 addresses and in-addr.arpa. for IPv4)."/>
        <errormessage severity="Warning" text="Could not find reverse address for 77.95.81.113 (113.81.95.77.in-addr.arpa.).&#xA;&#xA;PTR record(s) for the address could not be found in the .arpa-zone. (ip6.arpa. for IPv6 addresses and in-addr.arpa. for IPv4)."/>
    </errormessages>`

Thanks!

**Comment by timbru** [comment]
The original issue was resolved, and the issue raised in the last message is because of an issue that existed with the reverse zone for 77.95.81.112.
