### ISSUE TITLE
Authentication procedure for REST API

### ISSUE THREAD

**Issue by enp** [RIPE-NCC/whois#325]
Hi,

How to setup email/password pair for POST/PUT/DELETE requests? I see only password parameter in https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-Update.

I tried to execute example with my password only but got error:

```
<errormessage severity="Error" text="Authorisation for [%s] %s failed&#xA;using &quot;%s:&quot;&#xA;not authenticated by: %s">
  <args value="domain"/>
  <args value="..."/>
  <args value="mnt-by"/>
  <args value="..."/>
</errormessage>

```

**Comment by eshryane** [comment]
Hi Euene, you do not need to specify the maintainer when calling the REST API, only the password. Which maintainer(s) to authenticate against is determined by the server (and depends on the operation and the object type), but usually it's the mnt-by: attribute in the object itself.

The authentication model is explained in the Update reference manual: https://www.ripe.net/manage-ips-and-asns/db/support/documentation/update-ref-manual#section-54

I'll update the REST API documentation to clarify this.

**Comment by eshryane** [comment]
The error message you received mentions a domain object - the rules for domain authentication are explained further down: https://www.ripe.net/manage-ips-and-asns/db/support/documentation/update-ref-manual#section-62

**Comment by enp** [comment]
My PUT request (command is curl -X PUT -H 'Content-Type: application/xml' --data @domain.clean.xml https://rest.db.ripe.net/ripe/domain/x.x.x.in-addr.arpa?password=mypwd) contains:

```
<whois-resources>
<objects>
<object type="domain">
<source id="RIPE"/>
<attributes>
<attribute name="domain" value="x.x.x.in-addr.arpa"/>
<attribute name="descr" value="My network"/>
<attribute name="admin-c" value="MY-RIPE"/>
<attribute name="tech-c" value="MY-RIPE"/>
<attribute name="zone-c" value="MY-RIPE"/>
<attribute name="nserver" value="ns0.my.net"/>
<attribute name="nserver" value="ns1.my.net"/>
<attribute name="mnt-by" value="MY-MNT"/>
<attribute name="source" value="RIPE"/>
</attributes>
</object>
</objects>
</whois-resources>
```

How to identify myself in this case?

I can login by email and password into https://apps.db.ripe.net/search/query.html and I  see 'auth: SSO' for my email in mntner for modified domain.

**Comment by eshryane** [comment]
If you are modifying a domain object, then authentication is done against mnt-by mntners on the object itself.

The REST API currently only supports password authentication. So you need an auth: MD5-PW in the mntner, and supply the plaintext password as a query parameter on the update.

You can use SSO authentication to make updates directly using the website: https://apps.db.ripe.net/
