### ISSUE TITLE
Initial import issues. 

### ISSUE THREAD

**Issue by 0x4E0x650x6F** [RIPE-NCC/whois#329]
Tested on Slackware 14.1, and debian 7, with oracle java 1.8.71, on system with 16G memory 500Gb ssd hardrive. 

After inicial setup flowing the instructions on the wiki. 
the Setup-a-RIPE-Database-mirror-using-GRS-Import runned for 8h non stop, after close inspection i could find several exceptions in console.log, followed by a suspicious behavior executing a query to count the  number of rows in the mirroring database, as can be seen in the image between queries their are 915080 rows that are unaccounted for the behavior as observed for several hours while running the import. 

[
![roolback](https://cloud.githubusercontent.com/assets/1144303/12674436/e6619acc-c67a-11e5-8676-2778b2729d58.png)
![sql-errors](https://cloud.githubusercontent.com/assets/1144303/12674440/e8e63a28-c67a-11e5-9757-b2334103f1d2.png)

](url)

**Comment by eshryane** [comment]
Do you need to use replication? If so, we are using row-based logging, not statement based.
```
binlog-format=row
binlog-ignore-db=mysql
binlog-ignore-db=information_schema
max_binlog_size = 100M
```

If you don't need replication, try turning off binary logging altogether.

**Comment by timbru** [comment]
Since we didn't hear back I am closing this issue.
