### ISSUE TITLE
Display version earlier in the port43 query pipeline

### ISSUE THREAD

**Issue by job** [RIPE-NCC/whois#383]
It was brought to my attention that some database client software implementations would benefit from knowing earlier in the TCP stream which version of the database query service they are dealing with.

As it currently stands the database version string is displayed at the very end of the query output:

```
$ whois -h whois.ripe.net as15562
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to 'AS15476 - AS15705'

as-block:       AS15476 - AS15705
descr:          RIPE NCC ASN block
remarks:        These AS Numbers are assigned to network operators in the RIPE NCC service region.
mnt-by:         RIPE-NCC-HM-MNT
created:        2010-05-11T11:45:05Z
last-modified:  2014-02-24T13:15:16Z
source:         RIPE

% Information related to 'AS15562'

% Abuse contact for 'AS15562' is 'job@instituut.net'

aut-num:        AS15562
as-name:        SNIJDERS
descr:          Job Snijders
<SNIP>

% This query was served by the RIPE Database Query Service version 1.87.2 (DB-2)
```

Maybe it would be good to display the version after the `termsAndConditions()` output something like:

```
$ whois -h whois.ripe.net as15562
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf
%
% This query is served by the RIPE Database Query Service version 1.87.2 (DB-2)
...
```

**Comment by timbru** [comment]
Hi Job, if we do this, do we risk breaking clients that expect this string at the end? And if so, should we have it appear twice?

**Comment by bengan** [comment]
Shouldn't that output be for eyeballs only? I mean, how many versions of parsing the output isn't there out there. In worst case, one per person. It's actually more logical to do that in the RESTful API. That said. You can do a query first to see what version of the database there is.

whois -h whois.ripe.net -- '-q version'
