### ISSUE TITLE
Error in build  no main manifest attribute, in whois.jar

### ISSUE THREAD

**Issue by DavidPratama** [RIPE-NCC/whois#425]
I'm on progress to build regional whois server in my country
I'm trying to build with this instruction
mvn clean install -Prelease

and follow all instalation procedure carefully
but when I start whois server with ./whois.init start, I found this error message in var/console.log
"no main manifest attribute, in whois.jar". And I then can't start whois server successfully.

when I try to run java -jar whois.jar there is same error
no main manifest attribute, in whois.jar
Looks like maven doesn't generate Main-Class attribute in the MANIFEST.MF
Any ideas to solve this? Is this a bug or am I miss something? I'm using latest stable branch.

**Comment by eshryane** [comment]
Hi David,

just to confirm, when you create a release with 'mvn clean install -Prelease', the release jar is in whois-db/target/ , and is around 40MB in size.

I just ran a release build, and when I unzipped this jar file, i did find a META-INF/MANIFEST.MF, containing a main class:

Main-Class: net.ripe.db.whois.db.WhoisServer

I tried: java -jar whois-db-1.89-SNAPSHOT.jar 

and Java did try to start the application.

Can you check how you are building, and which jar you are using?  

A build without the "-Prelease" profile will produce a whois-db.jar WITHOUT the Main-Class: line in the MANIFEST.MF, and the jar will only be 8K in size.

**Comment by DavidPratama** [comment]
Thanks you for your assistance..
I'm using wrong jar file taken from /target/ 
issue closed..
