### ISSUE TITLE
Notification of RIPE Database changes does not include who did it

### ISSUE THREAD

**Issue by Gunni** [RIPE-NCC/whois#447]
When we receive a notification that someone modified our objects, we only get:

    Change requested from:

    - From-Host: xxx.xxx.xxx.xxx
    - Date/Time: Mon Aug 21 13:22:42 2017

Even when users are authenticated with SSO.

I'd like to suggest adding the authentication method and name the user used.

Example:

    Change requested from:

    - Auth: SSO: user@example.com
    - From-Host: xxx.xxx.xxx.xxx
    - Date/Time: Mon Aug 21 13:22:42 2017

Or:

    Change requested from:

    - AUTH: PGPKEY-XXXXXXXX
    - From-Host: xxx.xxx.xxx.xxx
    - Date/Time: Mon Aug 21 13:22:42 2017

Or something similar so that the authorization can be traced to a specific user or auth line.

**Comment by Gunni** [comment]
Either this was solved or i just started noticing this message in the notifications:

> Changed by SSO account: username@example.com

It is visible below the new version of the object.

I do not see that line in emails before 2017-05-26, so maybe it is a relatively new change.

**Comment by eshryane** [comment]
Hello, thanks for your report, and apologies for not replying earlier. 

Just to confirm, we added a notice of who changed the object to notifications in Whois 1.89, which we released to production on May 22nd. This is only possible where we can identify the user by the authentication mechanism they used (SSO or PGPKEY), it's not possible with password authentication.

Regards
Ed Shryane
RIPE NCC

**Comment by Gunni** [comment]
@eshryane i understand that, but in the case of password authentication, can you not add "Changed by auth MD5 xxxx?

p.s. we stopped using md5 probably 2 years ago so it does not affect us.
