### ISSUE TITLE
project whois-scheduler: Compilation failure

### ISSUE THREAD

**Issue by prakash5331** [RIPE-NCC/whois#492]
How to resolve **whois-scheduler: Compilation failure**

[INFO] Reactor Summary:
[INFO]
[INFO] whois ............................................. SUCCESS [4.673s]
[INFO] whois-rpsl ........................................ SUCCESS [24.444s]
[INFO] whois-client ...................................... SUCCESS [7.528s]
[INFO] whois-commons ..................................... SUCCESS [1:36:12.056s]
[INFO] whois-query ....................................... SUCCESS [18:23.899s]
[INFO] whois-nrtm ........................................ SUCCESS [4:02.792s]
[INFO] whois-update ...................................... SUCCESS [13:52.025s]
[INFO] whois-api ......................................... SUCCESS [6:12.999s]
[INFO] whois-scheduler ................................... FAILURE [4.234s]
[INFO] whois-db .......................................... SKIPPED
[INFO] whois-endtoend .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:19:25.222s
[INFO] Finished at: Fri Jul 20 17:15:30 IST 2018
[INFO] Final Memory: 45M/465M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project **whois-scheduler: Compilation failure**
[ERROR] /opt/whois-master/whois-scheduler/src/main/java/net/ripe/db/whois/scheduler/task/loader/LoaderSafe.java:[5,49] class, interface, or enum expected**

**Comment by eshryane** [comment]
Hi @prakash5331 I'm not able to reproduce this issue, can you provide some more details?
