### ISSUE TITLE
RDAP list resources associated with entity (org)

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [RIPE-NCC/whois#525]
compare https://rdap.arin.net/registry/entity/THEFA-3 with https://rdap.db.ripe.net/entity/ORG-FIL7-RIPE

```
$ curl https://rdap.arin.net/registry/entity/THEFA-3 | jq 'keys'
  "autnums",
  "entities",
  "events",
  "handle",
  "links",
  "networks",
  "notices",
  "objectClassName",
  "port43",
  "rdapConformance",
  "vcardArray"
]


curl https://rdap.db.ripe.net/entity/ORG-FIL7-RIPE | jq 'keys'
[
  "entities",
  "events",
  "handle",
  "links",
  "notices",
  "objectClassName",
  "port43",
  "rdapConformance",
  "vcardArray"
]
```

none of number resources is returned, making the query very much useless.

**Comment by eshryane** [comment]
Hello,

thanks for your feedback. I confirmed this is missing from our implementation, and I've updated [README.RDAP.md](https://github.com/RIPE-NCC/whois/blob/master/README.RDAP.md).

I'll also add a bug to our product backlog.

**Comment by jkldgoefgkljefogeg** [comment]
Is this fixed? In my use case this is one missing feature that renders RDAP useless.

It has been brought up on db-wg over a year ago https://www.ripe.net/ripe/mail/archives/db-wg/2018-March/005843.html.

**Comment by eshryane** [comment]
Hi @jkldgoefgkljefogeg this is not fixed yet. It's documented as a known issue in the [RDAP README](https://github.com/RIPE-NCC/whois/blob/master/README.RDAP.md#entity-does-not-include-networks), and it's in our product backlog to fix it. 

Some organisations have many, many resources associated with them, and we don't want to introduce any performance issue (response too large or too slow) with this change.

**Comment by jkldgoefgkljefogeg** [comment]
This is a major blocker to make RDAP usable for IPAM.

**Comment by eshryane** [comment]
@jkldgoefgkljefogeg Good to know, we will prioritise this issue when we next have time to work on the remaining RDAP issues. 

Is it enough to return top-level resources in the response? This will limit the size.  Or do you also need all more specific resources in the same response?

**Comment by jkldgoefgkljefogeg** [comment]
Only top level resources are good (actually preferred, need a way to filter out more specifics/related records otherwise).

**Comment by jkldgoefgkljefogeg** [comment]
Any update on this? Some clarification is needed on how to get all resources for an ORG/LIR. But in practice not all inetnum/inet6num objects seem to have org field set (despite RIPE DB documentation claims this field to be mandatory)

in whois I can do roughly the same by inverse lookup on mntner.

**Comment by eshryane** [comment]
Hello @jkldgoefgkljefogeg @rvdm thanks for your feedback.

We are currently implementing the NRO profile to make the RIPE RDAP service consistent with the other RIRs:
https://bitbucket.org/nroecg/nro-rdap-profile/raw/v1/nro-rdap-profile.txt

This work includes adding the missing "networks" and "autnums" elements to the entity response.:

```
5.1.2.  Other

   Each top-level entity object that has the "registrant" role for one
   or more IP networks MUST include a "networks" element containing only
   those IP networks.  The "networks" element MUST NOT be included in
   other types of entity object.

   Each top-level entity object that has the "registrant" role for one
   or more autnums MUST include an "autnums" element containing only
   those autnums.  The "autnums" element MUST NOT be included in other
   types of entity object.
```

You can expect to see this improvement in the next Whois release due in the coming months.
