### ISSUE TITLE
Load balancer does not have available server for client: rest.db.ripe.net

### ISSUE THREAD

**Issue by SMOK010** [RIPE-NCC/whois#535]
I don't have access to **rest.db.ripe.net** url. Also when i ping it from command line. I check and a browser redirect from this url to https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API. Why i can't send any request to **rest.db.ripe.net** - this url is presented in documentation as ripe api main address so i tried make some request to this but it failed in appliaction beacause of:

_Load balancer does not have available server for client: rest.db.ripe.net_

Can i make some requests to https://rest.db.ripe.net? If no what shall i do?

**Comment by eshryane** [comment]
This URL should be accessible over both HTTP and HTTPS, it's the API address for the RIPE database.

Can you try: https://rest.db.ripe.net/ripe/person/DUMY-RIPE

This should return the person object DUMY-RIPE.

Pings to this address are blocked.

**Comment by eshryane** [comment]
@SMOK010 Closing for now. If you continue to have an issue with the REST API, please let us know.
