### ISSUE TITLE
WHOIS REST API Delete RO via Python

### ISSUE THREAD

**Issue by mkhachfeh** [RIPE-NCC/whois#541]
Hi All,

My aim is to be able to delete route objects from RIPE using python + requests.

Depends on:
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-Delete

it worked for me while testing that on PERSON, but I can't do that for RO.
in RO, RPSL Object primary key is subnet itself, which contains slash with.

For example, I am trying to run both below on RIPE TEST via requests.delete:

https://rest-test.db.ripe.net/TEST/route/92.204.11.0%2F24?password=emptypassword
https://rest-test.db.ripe.net/TEST/route/92.204.11.0/24?password=emptypassword

But not working with the following error:
`<errormessage severity="Error" text="Not Found"/>`

I am not sure how to formalize subnet with slash within URL.

Could you please spot-light how to make it works?

An example also will be so appreicated.

**Comment by mkhachfeh** [comment]
We figured that out ^_^

So basically we need to use 2 variables (route + origin) as one primary key, so I used the following URL:
http://rest-test.db.ripe.net/test/route/92.204.11.0/24AS102

**Comment by eshryane** [comment]
@mkhachfeh Thanks for letting us know! And apologies that we weren't more helpful.

We need to improve our documentation, to make it clear that a route(6) key consists of both the prefix and origin.

**Comment by eshryane** [comment]
I've updated the wiki documentation with a description of the path parameters and examples.
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
