### ISSUE TITLE
StatusCode 429 TooManyRequests is not documented anywhere

### ISSUE THREAD

**Issue by fume** [RIPE-NCC/whois#555]
I'm getting a 429 status code but i can't find it documented anywhere. I perfectly know what it means, but i would like to know why i'm getting throttled (which are the limits?) so i could implement a better retry system.

thanks, regards

**Comment by cs-rb** [comment]
Only from digging through the code this document is refferenced, hope it helps. https://www.ripe.net/manage-ips-and-asns/db/support/documentation/aup

**Comment by eshryane** [comment]
Hello, the response body also includes a link to the documentation:
http://www.ripe.net/data-tools/db/faq/faq-db/why-did-you-receive-the-error-201-access-denied

I've also updated the wiki page with the 429 status code:
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-Lookup
