### ISSUE TITLE
unable to create object with POST to https://rest.db.ripe.net/RIPE/inet6num

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [RIPE-NCC/whois#608]
This is the HTTP POST (except URI and password)
https://webhook.site/#!/27505678-3ed5-4114-8d72-084be8c71bb0/e4a1c51c-2bb6-44b1-971d-8105b179dbe8/1

I used clear MD5-PW password for fb-neteng mntner (the original pw before md5), the entire url passed to `requests.utils.requote_uri`, auth is still failing even after I updated the password on mntner

I got 

> Authorisation for parent [inet6num] 2a03:2880::/29 failed
> using \"mnt-by:\"
> not authenticated by: RIPE-NCC-HM-MNT, mntner1

> Authorisation for [inet6num] 2a03:2880:100::/40 failed
> using \"mnt-by:\"\nnot authenticated by: mntner1, mntner2

**Comment by jkldgoefgkljefogeg** [comment]
It turned out I had a `+` in  password and `requests.utils.requote_uri` does not quote it properly (return has `+` as is). I changed md5 pw to be without `+` and it worked. 

Not sure if the backend can handle `+` correctly. Maybe RIPE DB should not allow md5 password with space or `+`?

**Comment by eshryane** [comment]
Hi @jkldgoefgkljefogeg thanks for your report, I've added a test to confirm that a plus or space character can be used in a maintainer's MD5 hashed password (commit 5977e69d4cd450bfb292ec4eeb2fbf6be94ebc18).
