### ISSUE TITLE
WHOIS REST API // Addition

### ISSUE THREAD

**Issue by netfreak98** [RIPE-NCC/whois#623]
Hey guys,

regarding your "WHOIS REST API" wiki article. Could you please make it a bit clearer on this page that setting up an md5 auth attribute in the maintainer object is necessary to use the API? I'm new to this topic and had some problems with the login at the beginning. After I found your note on the following page, it was clearer :)

https://www.ripe.net/manage-ips-and-asns/db/support/security/protecting-data

In my opinion this could make it easier for new users to get started with the RestAPI. Just as a kind hint :)

Best regards
Joey

**Comment by eshryane** [comment]
Hello Joey,

Firstly, apologies for the late reply, we are supporting the Whois repository on a "best effort" basis but this took a long time.

Thank you for your suggestion, I've extended the Authentication section of the REST API page, and added a reference to the Protecting Data page.

See https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API#user-content-authentication

Thanks for your feedback.
