### ISSUE TITLE
JAR is empty except for META-INF

### ISSUE THREAD

**Issue by amcfadden91** [RIPE-NCC/whois#624]
I've gone through the setup and I run `mvn clean install -Prelease`.  The resulting JAR I get is only 7.3KB and just has META-INF in it.  The manifest doesn't have a main class. I'm not getting any errors, but I am getting a wall of warnings.  I've run tee and grep with the output to get a list of all the warnings that I'm including.
[warning_output.txt](https://github.com/RIPE-NCC/whois/files/4450956/warning_output.txt)

**Comment by eshryane** [comment]
Hi @Ninjamoose91 the release jar is in the whois-db/target/ directory, it's about 50MB in size.
