### ISSUE TITLE
Support for recursive expansion of as-set to a list of ASNs

### ISSUE THREAD

**Issue by job** [RIPE-NCC/whois#72]
The IRRd daemon supports a non-standard WHOIS flag, I have copy/pasted from their manual: 

```
!i          Return members of an as-set or route-set. Optionally,
            recursively expand members of all sets within the named set.
                !iAS-ESNETEU     # non-recursive, don't expand
                                     # any embedded as-set's
                !iAS-ESNETEU,1   # expand any embedded as-set's
                !iRS-FOOBAR,1    # recusive expansion of a route-set
```

Here is an example conversation with the RADB Whois server:

```
Eleanor:~ job$ telnet whois.radb.net 43
Trying 198.108.0.18...
Connected to whois.radb.net.
Escape character is '^]'.
!iAS-STEFFANN-IPv6,1
A16
AS15562 AS57771
C
Connection closed by foreign host.
Eleanor:~ job$
```

Given the new database backend that the RIPE Whois Server now has, am I right to assume that this feature with this syntax now is possible to implement, at minimal server-sided processing cost? 

Kind regards,

Job

**Comment by timbru** [comment]
I am afraid that it dropped under the radar.

However, it should be feasible to do this. Can you indicate how useful this is to you and others. Is this something you would use on the command line, or can we expect heavy use of this feature by scripts? If so, we will need to be careful about the server load.

**Comment by jwbensley** [comment]
We'd like to see this feature too. It would help us to build upstream/downstream/peer prefix filters automatically using less hacky methods.

Currently:
```

bensley@htpc:~$ whois -h whois.ripe.net -T as-set -i members AS51551

% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

%ERROR:105: attribute is not searchable
%
% "members" is not an inverse searchable attribute.

%ERROR:101: no entries found
%
% No entries found in source RIPE.

% This query was served by the RIPE Database Query Service version 1.88 (HEREFORD)


```

**Comment by jkldgoefgkljefogeg** [comment]
FYI irrc can recursively expand as-set and route-set
https://github.com/codeout/irrc

**Comment by jwbensley** [comment]
That is true, but I don't even need to install irrc, I can do it natively on my Bash CLI:

`$for ASN in `whois -h whois.ripe.net -T as-set AS-UPDATA | grep members`; do whois -h whois.ripe.net -T route -i origin $ASN | grep route: | awk '{print $2}'; done
185.26.16.0/22
195.190.22.0/24
46.183.192.0/21
82.203.32.0/19
82.203.64.0/18
94.101.160.0/21
94.101.168.0/23
...
`
But ideally I think it would be best if the whois CLI tool supported it natively rather than having to use seperate tools.

**Comment by Gunni** [comment]
I recently made the exact same tool, except i did it in php and I call the ripe xml api instead. But nevertheless if this were one call to the api or whois, that would be useful.

**Comment by eshryane** [comment]
Hi all,

apologies this issue has been open for a long time. Is there still interest in having this feature in RIPE Whois? If so, I will add to our backlog for implementation.

Regards
Ed
