### ISSUE TITLE
how to register maintainer in https://rest-test.db.ripe.net/

### ISSUE THREAD

**Issue by sysmat** [RIPE-NCC/whois#777]
- https://rest-test.db.ripe.net/
- long time ago we have a maintainer TEST-DBM-MNT and using source TEST using MediaType.APPLICATION_XML
- but now we get error:

```xml
<errormessages>
        <errormessage severity="Error" text="Authorisation for parent [%s] %s failed&#xA;using &quot;%s:&quot;&#xA;not authenticated by: %s">
            <args value="inetnum"/>
            <args value="192.2.0.0 - 192.2.3.255"/>
            <args value="mnt-lower"/>
            <args value="CM2-MNT"/>
        </errormessage>
    </errormessages>
```

**Comment by sysmat** [comment]
we are using in Url with query param `"?password=****"` in production env(https://rest.db.ripe.net/)  it works but in test env not

**Comment by eshryane** [comment]
Hello @sysmat The TEST environment database is reset every night, you will need to also re-create the CM2-MNT maintainer.

https://www.ripe.net/manage-ips-and-asns/db/ripe-test-database
