### ISSUE TITLE
,app domains 

### ISSUE THREAD

**Issue by sinasaedi** [RIPE-NCC/whois#805]
.app domains are not support

**Comment by eshryane** [comment]
Hello @sinasaedi we don't support *forward* domain objects (i.e. the .app TLD) in Whois, as currently only *reverse* domain objects (i.e. with suffix in-addr.arpa / ip6.arpa / e164.arpa) are supported in the RIPE database.

To support forward domains, it's possible to fork the code and update the validation logic for domain objects.
