### ISSUE TITLE
delegated-ripencc-extended-latest from local filesystem

### ISSUE THREAD

**Issue by SaltyHash123** [RIPE-NCC/whois#810]
Hey there,

i haven't found any information in the Wiki whether i can provide a local version of delegated-ripencc-extended-latest
instead of fetching it using FTP.
Is it supported or is there any workaround?

Thanks in Advance :)

**Comment by eshryane** [comment]
Hello @SaltyHash123 

You can try replacing the property value with a `file://` URL, specifying the fully-qualified path to your own delegated stats file.

Regards
Ed Shryane
RIPE NCC
