### ISSUE TITLE
Maintainer webhook notifications

### ISSUE THREAD

**Issue by natm** [RIPE-NCC/whois#882]
Please could I submit a feature request for maintainer updates to support webhooks. This would allow RIPE NCC users to easily integrate RIPE DB change notifications in their system, for example posting DB changes into Slack, NodeRED or other internal systems.

For example `NAT-MNT` today is...

```
mntner: NAT-MNT
descr: Nat Morris
org: ORG-NAT2-RIPE
admin-c: NAT-RIPE
tech-c: NAT-RIPE
auth: SSO nat@nuqe.net
mnt-by: NAT-MNT
upd-to: ripe@nuqe.net
notify: ripe@nuqe.net
mnt-nfy: ripe@nuqe.net
source: RIPE
```

It could have additional `upd-to-webhook` and `notify-webhook` lines:

```
mntner: NAT-MNT
descr: Nat Morris
org: ORG-NAT2-RIPE
admin-c: NAT-RIPE
tech-c: NAT-RIPE
auth: SSO nat@nuqe.net
mnt-by: NAT-MNT
upd-to: ripe@nuqe.net
upd-to-webhook: https://webhooks.nat.ms/ripe/upd-to
notify: ripe@nuqe.net
notify-webhook: https://webhooks.nat.ms/ripe/notify
mnt-nfy: ripe@nuqe.net
source: RIPE
```

This would allow a lot of flexibility on the part of the RIPE DB user and save having to parse emails. I would suggest the webhook attributes are not exposed when querying the maintainer objects by other users, in order to protect the webhook endpoints. Also the requests POST'd to them by the NCC should have a signature.

Thank you.

**Comment by eshryane** [comment]
Hello Nat, can you email the DB-WG with your request: https://www.ripe.net/mailman/listinfo/db-wg/

If the community finds this feature useful, we can look into adding it to Whois.

In the meantime, you could add this feature using NRTM to notify you of Whois updates:
https://www.ripe.net/manage-ips-and-asns/db/nrtm-mirroring

And perhaps parse a remarks: or descr: attribute on the update to trigger a webhook.

**Comment by natm** [comment]
Thanks for the quick response, yes I'll start a thread on the database working group list.
