### ISSUE TITLE
Better documentation of the offset query parameter

### ISSUE THREAD

**Issue by Sphatch** [RIPE-NCC/whois#952]
Hi There,

I'm reaching out in hopes of receiving some additional details on how to use (pagination with ripe) which appears to be the offset parameter.

Can someone please provide an example or better detail on how this can be used? When I attempt to use the parameter it fails to provide a "next" attribute or anything related to pagination.

Thank you!

**Comment by Sphatch** [comment]
So, I think I figured out how this thing works. It's 0 based and returns an empty list when the pagination is complete. Please let me know if that is correct?

I'd also suggest adding this nugget of information to the documentation.

Best

**Comment by eshryane** [comment]
Hi @Sphatch Correct. We implemented pagination in #441 for the DB web application query page, but didn't document the changes for end users. We will improve the documentation.

You can see it working at https://apps.db.ripe.net/db-web-ui/query with the network inspector. We didn't need to know the total number of results, we start at ```0``` and we stop paginating if less than the ```limit``` is returned.

**Comment by Sphatch** [comment]
Hi @eshryane, Thank you for the rapid fire response! and that is a lovely example. I now understand that you must set a limit to -n objects and use the offset to retrieve the next -n range.

Example:

query #1 / limit: 20 offset: 0
query #2 / limit:20 offset: 20 (fetches the next 20) 

... run until the objects list is empty


Thanks again!
